### ISSUE TITLE
problem with changing password

### ISSUE THREAD

**Issue by prtome** [saintedlama/passport-local-mongoose#103]
Hello
I have again a problem when changing a user password. It worked at some point, but now it does not anymore (always like that isn't it?)
here is my code
 Account.findByUsername(username, function(err,user) {
    if (err) { 
            return res.send({ msg: req.i18n.t('users.pbupdpwd')});
            }

    if (!user) {
      return  res.send({ msg: req.i18n.t('users.pbupdpwd')});
    }
   user.setPassword(req.body.newpwd, function(err, user) {
     if (err) {
         return  res.send({ msg: req.i18n.t('users.pbupdpwd')});
    }
  //until here all goes well
   user.save(function(err) {
      if (err) {
        console.log("/user/userupdpwd: user save error !!!", err);
        return  res.send({ msg: req.i18n.t('users.pbupdpwd')});
      }
      return res.send( {msg: req.i18n.t('users.pwdupdated')});
   });
   });
  });

The error is at the save level, I get this message in the log

/user/userupdpwd: user save error !!! { [ValidationError: DrugAccount validation failed]
  message: 'DrugAccount validation failed',
  name: 'ValidationError',
  errors: 
   { _id: 
      { [ValidatorError: Cast to ObjectId failed for value "[object Object]" at path "_id"]
        properties: [Object],
        message: 'Cast to ObjectId failed for value "[object Object]" at path "_id"',
        name: 'ValidatorError',
        kind: 'cast',
        path: '_id',
        value: [Object] } } }

What am I doing wrong ? I know this is a mongoose error, but why now ?

Thanks - Pat
NPM is 2.11.2, express 4.12,passport-local-mongoose 1.2.0, mongoose 4

**Comment by saintedlama** [comment]
I know this error :smile_cat: The object _id passed in req.body is a string and can thus not be cast to a mongodb ObjectId. Before passing the body directly to passport-local-mongoose which passes this object to mongoose you'll need to convert the _id field of the body:

```javascript
req.body._id = mongoose.Types.ObjectId(req.body._id);
```

**Comment by prtome** [comment]
Thanks but I am not sure I understand where req.body._id comes from
I call findByUsername
which gives me back user
which has a user._id
 then I do user.setPassword
should I do user._id = mongoose.Types.ObjectId(user._id);  ?
before calling user.save  (where there is the problem) or even before user.setPassword ?

Thanks again

**Comment by prtome** [comment]
More confused now ... I printed user as given back by findByUsername. 
user { salt: 'cda14137d8ac5836240fd842a4334dfff89834c96ea43db4df9d17511b2a07c8',
  hash: 'c2e71b0e3431b6d1b38fb22adcb8d01717778174850a15f0fe825df74ea177db0447dd029318a1bc4f5dc5d81a1e7855a31234f165ef6bb2c1b798c96b435de4c6190633ad1d87c29a34bc46b5d18948adfe5d2fe1fd93b6b4a623509cd58b7e177a0a9b0ad3513bcb425a42d46e9a895f3d56f69716d17f4701097b05ef40dd792ac0074b7f5b1c1df4100d967df00326db3ab0b4a37aa12412039a2d376b314c9e17b8af8654661d51c22b72bb654f56e6ceea1ff8e4efd7dec4ad5a08890ddf2332afcb07edcd9a39fa5dfbaad4ae234e4f2165171af98979e8f46cb86561fd6ac6cb1b84d8d6cd98ffc62446476419c412a5b159b955702dd5904824b161797f25920bb4eeb0529cb44d3bd3343ad74ada6639c50cc7abd4c938789b15ff51861adcef5600389493016ed539e257cd422eebbb16490f67d3528efa3c057dcfdb14e94240626b76099c92d90205aa699b10a5ab48a360920f4a18b72385973c6610e6f9c3eea99a62dcda2e324363f48ec398655f28d944003e46cd117fa93309362cdca6fbb7b7b4d92da9032fa5f8059d0d12a0619f7c5544a6c6e0ef2777bf2753b4f9732010a56ae193b95dcd063a259a1088b406bf9b6fa02c2dc4b9e44a6101a9b21789ebae0d6ea2d540abbbc7cfa42e3875964ed3226643df63dc695c142cb98e76535eba7807eb0a4a8734c826d03d8916b6da630df9f775df5e',
  dbname: 'mydb',
  username: 'cmyname',
  nomuser: 'myname',
  role: 'STANDARD',
  mylang: 'it-IT',
  __v: 0,
  lastlogin: Sat Sep 12 2015 11:41:04 GMT+0200 (CEST) }

I don't have _id ? so findByUsername does not give that back? maybe that is where the problem is, user._id is undefined ....

**Comment by prtome** [comment]
I might have found the error, a path in one of the models which was conflicting with a reserved work. After changing that path name - it works!

**Comment by saintedlama** [comment]
:+1:
