### ISSUE TITLE
Duplicate key error using email as username

### ISSUE THREAD

**Issue by dtouch3d** [saintedlama/passport-local-mongoose#106]
Hi,

After the first user registers successfully, no other user can. Mongoose says

>WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error index: >db.accounts.$username_1 dup key: { : null }...

Does this mean that it still queries for a username field which is null and a new user cannot register because he also has a null username field ?

My schema:

```
var Account = new Schema({
    var name: String,
    var email: String
}

Account.plugin(passportLocalMongoose, { 
    usernameField: 'email'
});

```

Also, I tried setting usernameQueryFields to 'email' but it crashes with 

>TypeError: undefined is not a function
>at module.exports (.../passport-local-mongoose/lib/passport-local-mongoose.js:23:37)

Although the options object has usernameQueryFields: ['email'] set correctly by default.

**Comment by dtouch3d** [comment]
Also, I removed all accounts without a username field and I could register again but just for once, so the null username theory from above checks out.

**Comment by bexcite** [comment]
I had the same issue until I dropped the the table 'Account' completely. I think the cause war in the indexes that was created when I first time executed the model without setting usernameField.

**Comment by dtouch3d** [comment]
You are right! I just dropped the index for the username field and all is good. Thanks!

**Comment by saintedlama** [comment]
Thanks @bexcite for the hint

**Comment by chrisfortin16** [comment]
I also had this issue, I solved it by removing the index and dropping my database, re-creating it and it worked, thanks.

**Comment by kiknag** [comment]
@bexcite I was trying to solve this problem whole day and finally I saw your answer 👍  Thanks

**Comment by isaachinman** [comment]
Also just encountered this problem, 2.5 years after the original user. Would be nice to have a more detailed error message.

**Comment by alexratiu** [comment]
> I had the same issue until I dropped the the table 'Account' completely. I think the cause war in the indexes that was created when I first time executed the model without setting usernameField.

Thanks dude this works for me :)
