### ISSUE TITLE
Using function length to determine which version of a function to use is error prone

### ISSUE THREAD

**Issue by wraithan** [saintedlama/passport-local-mongoose#111]
https://github.com/saintedlama/passport-local-mongoose/blob/c871828a55fd809b6382b1c7808f8ac5f785fe77/index.js#L52

I'm biased in this, because I work on the new relic node module and we wrap up many of the core APIs for timing reasons, without adding more overhead or more `eval`s (or things that proxy to `eval` like `new Function()`) we don't have a way to wrap up functions and retain their argument list length.

We solve the same problem you are solving by doing version detection and branching that way, generally this is safer, less able to be impacted by other libs, and need only be done once per process to setup which one you are going to use.

This also creates more self documenting code, as you can look at the code and see the version the difference was introduced, without having to sleuth through the docs/core source to find the version that introduced the change.

**Comment by wraithan** [comment]
If it is acceptable to change this to do a version check against node, I'll write the PR for it.

**Comment by saintedlama** [comment]
A PR would be more than welcome :dancers:

**Comment by saintedlama** [comment]
Is fixed in latest version `4.0.0`
