### ISSUE TITLE
User validation failed

### ISSUE THREAD

**Issue by bsass1** [saintedlama/passport-local-mongoose#112]
I get Mongoose validation error for path password:  
message: 'Validator failed for path `password` with value `0`',
        name: 'ValidatorError',
        kind: 'user defined',
        path: 'password',
        value: 0 } } }

I know that passport-local-mongoose creates hashing and salt paths but it doesn't fill in the passoword path. I made it not required and remove the password path altogether still get the mongoose validation error 

var userSchema = new mongoose.Schema({
  email: {
    type: String,
    required: true,
    unique: true
  },
  password: String,
});

Is there something I need to override?

**Comment by saintedlama** [comment]
You should not store a password or define a password field at all. The plugin cares about storing hash and salt where passport cares about forwarding password and username to passport-local-mongoose
