### ISSUE TITLE
How to validate a password?

### ISSUE THREAD

**Issue by babbelnedd** [saintedlama/passport-local-mongoose#114]
I want to add a feature to my site which enables changing a password. But I want to add an requirement to provide the current password along the new password. 

Currently I use `instance.authenticate(currentPassword, cb);` and the third argument of the callback to ensure the password is correct. Since the user have to be authenticated to update his password this way kinda feels wrong.

Question: is there a more obvious way to test a password?

**Comment by saintedlama** [comment]
`ìnstance.authenticate` is fine. It has no side effects and IMHO is sound when used in code. If you want a function alias like 'checkOldPassword' you could add a `schema.methods.checkOldPassword` that calls `this.authenticate`.
