### ISSUE TITLE
Converting a login/registration username to all lowercase

### ISSUE THREAD

**Issue by asipser** [saintedlama/passport-local-mongoose#116]
Hi Saintedlama,
I have been playing around with passportlocalmongoose and have followed the tutorial on your github page for it to set the authentication system up. My issue comes up when two users make the same username but contain different capitalization, the system thinks they are different usernames and doesn't throw an error. For registration I can req.body.toLowerCase() when creating a new Account, however for Logins you simply use passport.authenticate(). Is there any way I can make sure the username has been put to all lowercase before it runs passport.authenticate? If there is a setting in passportlocalmongoose to fix this issue how would I go by implementing this? 

Thanks,
Aaron.

**Comment by imlbf** [comment]
@asipser You probably don't need this answer anymore, but anyway, in your Users model, just add the options after the module.
`User.plugin(passportLocalMongoose, {usernameLowerCase: true});`
