### ISSUE TITLE
Passing req.user directly to the template is a good idea?

### ISSUE THREAD

**Issue by gpkc** [saintedlama/passport-local-mongoose#117]
Hi,
it seems common on the examples to pass req.user to the template directly, but that also sends the hash and salt fields.
If I'm going, for example, to save this as an javascript object on the template, the object would be sent to the user untouched.
Am I right to suppose that this would represent a security flaw? Specially if not under a SSL connection.

**Comment by iamtekeste** [comment]
@gpkc Do you mind sharing what you ended up doing?

**Comment by gpkc** [comment]
@iamtekeste I have no idea what exactly I did at the time, it's been a little while. But I suppose you should simply not store the hash and salt as a javascript object. You can, however, pass that to a template if you're sure you're not storing it anywhere.

**Comment by iamtekeste** [comment]
@gpkc Thank you for the reply! I will have to manually remove them then.
