### ISSUE TITLE
should we delete hashOption and salt option from user ?

### ISSUE THREAD

**Issue by Daniel-Xu** [saintedlama/passport-local-mongoose#120]
Right now, we have hash and salt in user document, 
![image](https://cloud.githubusercontent.com/assets/548144/13168815/7047f914-d6ae-11e5-9830-1aeb0df9be43.png)

should we delete them before passing them out using callback? 
In `authenticate`
```
      if (scmp(hash, user.get(options.hashField))) {
        if (options.limitAttempts) {
          user.set(options.lastLoginField, Date.now());
          user.set(options.attemptsField, 0);
          user.save();
        }
+++
        var userObj = user.toObject();
        delete userObj[options.hashField];
        delete userObj[options.saltField];
        return cb(null, userObj);
+++
      } else {
```

and in `setPassword`
```
        user.save(function(saveErr) {
          if (saveErr) {
            return cb(saveErr);
          }

          var userObj = user.toObject();
          delete userObj[options.hashField];
          delete userObj[options.saltField];
          cb(null, userObj);
        });

```

**Comment by BrandonCopley** [comment]
I would recommend that.

**Comment by saintedlama** [comment]
:+1

**Comment by saintedlama** [comment]
Would recommend removing hash and salt. Why expose something that is not needed

**Comment by Daniel-Xu** [comment]
@saintedlama  I mean should I do this in my own middleware, or should I make a pull request for this? 
the code I posted are methods in `index.js`

**Comment by BrandonCopley** [comment]
@Daniel-Xu I don't believe this should be done within the passport-local-mongoose code, maybe some new code could be added, new functions, that getUserData but missing the salt/hash

**Comment by Daniel-Xu** [comment]
Thanks @BrandonCopley
