### ISSUE TITLE
Throws error 'select cannot be used with count' when making parallel requests with reused query

### ISSUE THREAD

**Issue by Gentlee** [saintedlama/passport-local-mongoose#124]
I'm trying to reuse query to make two parallel requests and got an error `select cannot be used with count`.

    var query = User.find({}) // here can be very long query
    async.parallel([
        function(callback) { query.exec(callback) },
        function(callback) { query.count().exec(callback) }
    ], function(err, results) {
        if (err) return next(err)
        res.json({
            data: results[0],
            totalCount: results[1]
        })
    })

1) If i use `async.series` instead of `async.parallel`, all works perfectly with the same query object.

2) If i create new query for each request and execute it parallely, than all works perfectly too.

    async.parallel([
        function(callback) { User.find({}).exec(callback) },
        function(callback) { User.find({}).count().exec(callback) }
    ], function(err, results) {
        if (err) return next(err)
        res.json({
            data: results[0],
            totalCount: results[1]
        })
    })

3) If i don't plugin User schema with passport-local-mongoose, i don't have this problem at all, using the same parallel code.

**Comment by Gentlee** [comment]
Added tests for this issue, https://github.com/saintedlama/passport-local-mongoose/pull/125

**Comment by saintedlama** [comment]
This is not really a passport-local-mongoose issue because if you try not to use passport-local-mongoose but add schema fields that passport-local-mongoose manually and issue the query as in pr #125 the mongoose error pops up:

Try this without using passport-local-mongoose in your test:

```
var UserSchema = new Schema({
      username: {type: String, unique: true },
      hash: {type: String, select: false},
      salt: {type: String, select: false}
    });
```

**Comment by Gentlee** [comment]
Ok, sorry then, i'll report to mongoose. Thanks.
