### ISSUE TITLE
Is password verification using constant-time checks?

### ISSUE THREAD

**Issue by deanc** [saintedlama/passport-local-mongoose#134]
I took a closer look at the code behind this module today and it's using `crypto.pbkdf2`. I'm not 100% sure but it doesn't look like it's doing a constant-time check. Obviously the maxlimits helps prevent agains this to some extent, but it's good practice to do this.

Can you confirm if you're using this feature? I found this library that implements constant time checking:
https://github.com/davidmurdoch/easy-pbkdf2

**Comment by saintedlama** [comment]
Passport-local-mongoose uses the same hash algorithm implementation from node.js crypto module as https://github.com/davidmurdoch/easy-pbkdf2 does. easy-pbkdf2 uses a constant time based string comparison (implemented in function `constantTimeStringCompare`). Passport-local-mongoose uses the `scmp` module to do this job. I'm not 100% sure if the pbkdf2 implementation is constant time based but passport-local-mongoose is not more vulnerable to time based attacks as easy-pbkdf2 is.
