### ISSUE TITLE
Password field on User schema

### ISSUE THREAD

**Issue by woniesong92** [saintedlama/passport-local-mongoose#145]
In `User` Schema, you shouldn't have a `password` field, right?
This [tutorial](http://mherman.org/blog/2013/11/11/user-authentication-with-passport-dot-js/#.V2z6bJMrLeQ) that's mentioned in the README defines a `password` field but it doesn't make sense to me.

**Comment by spezzino** [comment]
you shouldn't have a password field. the password is stored in the hash field.
