### ISSUE TITLE
multiple local strategies and req.user

### ISSUE THREAD

**Issue by SOSANA** [saintedlama/passport-local-mongoose#182]
will this plugin allow mutliple local strategies with admin, user, member models?

or do we have to follow passport-local with only one user model with role to utilize the ```req.user```?

@saintedlama @fhemberger @theanimal666 @bachp @niftylettuce ?

**Comment by niftylettuce** [comment]
just add a field called `group` to your user schema, set default to `user` and then make it enumerable `user`, `admin`

**Comment by SOSANA** [comment]
@niftylettuce thanks :)

**Comment by niftylettuce** [comment]
@SOSANA when people log in, just check it like this...

```
app.all('/admin/*', function(req,res,next) {
  if (!req.isAuthenticated() || req.user.group !== 'admin') return res.sendStatus(401);
  res.send('you are an admin!');
});
```
