### ISSUE TITLE
Validate password before change.

### ISSUE THREAD

**Issue by charliebrink** [saintedlama/passport-local-mongoose#194]
I want to validate the current password before changing it.

I've referenced [this](https://github.com/saintedlama/passport-local-mongoose/issues/114) but  `this.authenticate()` is not doing anything -- no callback or errors.

Am I missing something obvious?

controller:

```
User.findById(password.userId, (err, user) => {
    if (err) return res.status(400).send({ message: err });

    user.validatePassword(password, (err) => {
      if (err) return res.status(400).send({ message: err });

      // password validation was ok
      user.setPassword(password.new, () => {
        user.save((err) => {
          if (err) return res.status(400).send({ message: err });

          req.login(user, function (err) {
             if (err) return res.status(400).send({ message: err });
             res.json(user);
          });
        });
      });
    });
  });
```

model:

```
User.methods.validatePassword = function (password, callback) {
  this.authenticate(password, callback);
};
```

**Comment by mrsteele** [comment]
Related to #127. I made a mention that this approach would be the best possible approach.

**Comment by charliebrink** [comment]
Thanks, got it to work but like you say, it feels heavy to authenticate again.
I also mapped the error message from 'Password or username is incorrect' to 'Current password is incorrect'.
