### ISSUE TITLE
async/promises supported register method

### ISSUE THREAD

**Issue by niftylettuce** [saintedlama/passport-local-mongoose#218]
e.g.

```js
Users.plugin(passportLocalMongoose, config.auth.strategies.local);

// https://github.com/saintedlama/passport-local-mongoose/issues/218
Users.statics.registerAsync = function (data, password) {
  return new Promise((resolve, reject) => {
    this.register(data, password, (err, user) => {
      if (err) return reject(err);
      resolve(user);
    });
  });
};
```

But we should build this into `Users.register`, not have two sep funcs.

**Comment by niftylettuce** [comment]
I edited example given in previous comment to be valid btw.

**Comment by saintedlama** [comment]
Looks good to me

**Comment by alexandernanberg** [comment]
Any status on when this might be implemented? There are some discussion about adding promises support for the base passport package as well [here](https://github.com/jaredhanson/passport/issues/536)

**Comment by niftylettuce** [comment]
I'd suggest that instead of just adding this helper function, since Mongoose 4.x directly supports and uses promises, we should just completely rewrite this package to use Promises (and drop callback support).

**Comment by saintedlama** [comment]
@niftylettuce +1

**Comment by ctrlplusb** [comment]
You could support both too? I am currently monkey patching it within my code:

```js
const cbAuthenticate = userSchema.methods.authenticate

userSchema.methods.authenticate = function authenticate(password, cb) {
  return new Promise((resolve, reject) => {
    cbAuthenticate.call(this, password, (err, result) => {
      if (err) {
        reject(err)
      } else {
        resolve(result)
      }
      if (typeof cb === 'function') {
        cb(err, result)
      }
    })
  })
}

module.exports = mongoose.model('User', userSchema)
```

**Comment by valeco** [comment]
I tried to promisify `register` function with [`es6-promisify`](https://www.npmjs.com/package/es6-promisify) and [`util.promisify`](https://nodejs.org/api/util.html#util_util_promisify_original) but both throw this error:

```
Right-hand side of 'instanceof' is not an object

TypeError: Right-hand side of 'instanceof' is not an object
    at schema.statics.register (/home/vale/Development/Personal/plande/plande-api/node_modules/passport-local-mongoose/index.js:187:16)
```

@niftylettuce's snippet solves the problem. Thank you!

Hopefully this helps someone else.

**Comment by saintedlama** [comment]
Current releases support async/await/promises

**Comment by Koviac** [comment]
then why do VS Code and passport-local-mongoose type declaration expect a function even when there's an await statement before it eg. authenticate(), findByUsername() etc @saintedlama

**Comment by z-mp** [comment]
> I tried to promisify `register` function with [`es6-promisify`](https://www.npmjs.com/package/es6-promisify) and [`util.promisify`](https://nodejs.org/api/util.html#util_util_promisify_original) but both throw this error:
> 
> ```
> Right-hand side of 'instanceof' is not an object
> 
> TypeError: Right-hand side of 'instanceof' is not an object
>     at schema.statics.register (/home/valeco/project/node_modules/passport-local-mongoose/index.js:187:16)
> ```
> @niftylettuce's snippet solves the problem. Thank you!
> 
> Hopefully this helps someone else.
> 
> **Edit:** This code was throwing the error:
> 
> ```js
> exports.register = async (req, res, next) => {
>   const newUser = new User({ email: req.body.email, name: req.body.name })
>   const register = promisify(User.register)
>   await register(newUser, req.body.password)
>   next()
> }
> ```
> 
> Using the @niftylettuce's approach:
> 
> ```js
> exports.register = async (req, res, next) => {
>   const newUser = new User({ email: req.body.email, name: req.body.name })
>   await User.registerAsync(newUser, req.body.password)
>   next()
> }
> ```

Hey Folks, just updated my project with latest passport-local-mongoose - wanted to leverage the new async/await syntax. However, registerAsync leads to "TypeError: _account2.default.registerAsync is not a function" Any idea of what is wrong? Plugin is configured as pointed out in the docs. My func is `async function registerAccount(email, password, verToken) {
 .........

  try {
    const newAccount = new Account({ email: email})
    await Account.registerAsync(newAccount, password)
    .............. 
    return .....
    
	} catch(err) {
    console.log('err is ', err)
    return err;
  }
}`

**Comment by SirPhemmiey** [comment]
Hi @valeco it's not working. Where does `registerAsync` come from?

**Comment by sethisidore** [comment]
@SirPhemmiey. the method registerAsync has been removed in favour of 'register' which now returns a promise if no callback is passed to it. So you could use it as below: 
const user = await User.register('username', 'password');
await user.save();
hope this helps

**Comment by SirPhemmiey** [comment]
Thanks @sethisidore 
The `registerAsync` is actually a static method and not a built-in method. 
But thanks for the heads up.

**Comment by niftylettuce** [comment]
@saintedlama 	just wanted to chime in and thank you for adding async/await support in 5.x
