### ISSUE TITLE
Support for Two types of Users login

### ISSUE THREAD

**Issue by pampas93** [saintedlama/passport-local-mongoose#240]
Similar to this [issue](https://github.com/jaredhanson/passport/issues/50),

I wanted two types of users logging in (User, Client). Is it possible to create two local strategies for each and how exactly do I use seriealizeUser and deserializeUser?

`passport.use(new LocalStrategy(User.authenticate()));
passport.use(new LocalStrategy(Client.authenticate()));`

But then, I'm not finding a way to serialize and deserialize the user. I apologize for this not an issue with the module, but just a question. Thanks

**Comment by leoyli** [comment]
I'm not letting my app firing `passport` all the time, only for those page needed to be authenticated via a middleware, where I introduced `passport` then populate `req.user` into `req.session.user`(reduced), my session is kept in my DB. The benefits by this is now you have choice to decide which middleware should be trigger and so which strategies want to be used, then you can also merge them together in another middleware easily.

**Comment by pampas93** [comment]
Thanks @leoyli. I actually went through another approach and worked for me. [This](https://stackoverflow.com/questions/48831211/support-for-multiple-user-types-by-passport-local-mongoose-node-js/48832614#48832614) is what I did.
