### ISSUE TITLE
SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by bfheythem** [saintedlama/passport-local-mongoose#241]
![screenshot from 2018-03-01 13-59-34](https://user-images.githubusercontent.com/22716581/36850475-384c2060-1d67-11e8-91c6-e35cf7c6507d.png)
  I receive that error when starting the server , my code is correct I dont know why I am getting this

**Comment by saintedlama** [comment]
Version 5.0.0 made a breaking change by not supporting node versions below 6. See changelog and .travis.yml for details
