### ISSUE TITLE
Does this plugin support social (Facebook/Google) auth?

### ISSUE THREAD

**Issue by isaachinman** [saintedlama/passport-local-mongoose#242]
Wondering if this plugin supports `FacebookStrategy`, `GoogleStrategy`, etc. I don't see documentation anywhere on it, but assume it would be a high priority.

If so, how are ID references stored, etc?

**Comment by saintedlama** [comment]
What do you exactly mean by "supports"? Passport-local-mongoose itself only handles password authentication while other passport plugins will handle facebook and google authentication
