### ISSUE TITLE
Internal working of passport.authenticate (login part)

### ISSUE THREAD

**Issue by pampas93** [saintedlama/passport-local-mongoose#244]
So, right now, to login and authenticate a user, we're doing the following,

`passport.authenticate('local')(req, res, function () {`
       `           res.redirect('/profile');`
 `     });`

How exactly is this working without passing the username or password anywhere into the authenticate function? Because, its assuming that username is stored as req.body.username and password as req.body.password; But when I change the name of input field in the front-end to passcode or something else, It doesn't work.

**Comment by saintedlama** [comment]
This part of the code is done by passport-local. passport-local supports using different parameter names. passport-local-mongoose does not do any magic here but rely on passport-local
