### ISSUE TITLE
authenticate() method promise not throwing error

### ISSUE THREAD

**Issue by SherloxFR** [saintedlama/passport-local-mongoose#246]
**My setup:**
```json
{
  "os": "Ubuntu 17.10",
  "node": "9.11.1",
  "npm": "5.6.0",
  "mongoose": "4.5.9",
  "passport": "0.3.2",
  "passport-local-mongoose": "5.0.0"
}
```

Hi,
I was very happy to see you added promises to your project, because I like working with them.

Unfortunately, the `authenticate()` isn't having the excepted behavior, if the user is not found (bad username / password), it doesn't throw an error as it should.
instead it is resolving:
```
{
  user: false,
  error: {
    IncorrectPasswordError: Password or username is incorrect
    at PBKDF2.ondone (/home/cdiet/workspace/CDIET-workspace/CDIET/node_modules/passport-local-mongoose/lib/authenticate.js:75:32)
    name: 'IncorrectPasswordError',
    message: 'Password or username is incorrect'
  } 
}
```

**Comment by SherloxFR** [comment]
Seems the problem is:
```
authenticate(user, password, options, (err, user, error) => err?reject(err):resolve({ user, error }))
```
Why is there one `err` at the right place, then `user`, then an additional `error` at the end ? Which is not checked by the promise.

**Comment by saintedlama** [comment]
The reason for this is that `err` is a technical error while `error` is a authentication relevant error. In case a password does not match, authenticate does not throw but return an empty user and an error object holding more information what went wrong

**Comment by SherloxFR** [comment]
Ok, can we get this `error` object in a promise throw if the authentication fail ? It is pretty annoying not to be able to access those more informations if an authentation error occur ...
I can PR if you are willing to.

Thanks in advance
