### ISSUE TITLE
How do I compare password

### ISSUE THREAD

**Issue by Filliposniper** [saintedlama/passport-local-mongoose#252]
Hello, i wish to check the password of a currently logged in user with the one stored in the database, as i would like to confirm it is the user, before they can enable some options in their dashboard like 2fa etc.
but i don't have a clue of that and have not seen a function that handles that in passport-local-mongoose. I have tried using bcrypt for that but it throws error..

  ```
   router.post("/enableTwoFa/:id", isLoggedIn, isVerified, function(req, res){
if(req.isAuthenticated){
    User.findById(req.params.id, function(err,found){
    if(err){
        res.redirect("back")
        res.send('User not found with the proper ID')
    } else {
        if(req.body.accountPassword){
            console.log(found)
            bcrypt.compare(req.body.accountPassword,found.password, function(err,success){
                if(err){
                    console.log(err)
                    res.send('There was a problem somewhere')
                } else {
                    console.log(success)
                    res.send('password hashed')
                }
            })

        } else {

                res.send('Please input your account password!!')
        }
    }
})
} else {
    res.send('You are not authorized for this request')
}

})
```

the error am getting from bcrypt, i have also asked the question in stacoverflow but no reply yet [https://stackoverflow.com/questions/50957819/how-to-compare-password-with-bcrypt-in-passport-local-mongoose](url)

`Error: data and hash arguments required
    at Object.compare (/home/ubuntu/workspace/bit-main/main/node_modules/bcrypt/bcrypt.js:209:17)
    at /home/ubuntu/workspace/bit-main/main/routes/dashboard.js:448:24
    at Query.<anonymous> (/home/ubuntu/workspace/bit-main/main/node_modules/mongoose/lib/model.js:3928:16)
    at /home/ubuntu/workspace/bit-main/main/node_modules/kareem/index.js:297:21
    at /home/ubuntu/workspace/bit-main/main/node_modules/kareem/index.js:135:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

**Comment by nikwen** [comment]
The [User.authenticate(password, [cb])](https://github.com/saintedlama/passport-local-mongoose#authenticatepassword-cb) function should be what you're looking for.
