### ISSUE TITLE
User.createStrategy Not Enabling Custom UsernameField Options

### ISSUE THREAD

**Issue by david-gagne** [saintedlama/passport-local-mongoose#262]
I've followed the instructions as written [here.](https://github.com/saintedlama/passport-local-mongoose#simplified-passportpassport-local-configuration)

However, when I submit a test user to the form on on signup page, it either _silently_ fails (i.e. loads until timeout) or it still causes the `MissingUsernameError: No username was given`.

Please advise.

**Comment by Filliposniper** [comment]
Ensure that you are passing a username req.body (req.body.username) on users registration.
