### ISSUE TITLE
[Doc] usernameCaseInsensitive not mentioned

### ISSUE THREAD

**Issue by pjdauvert** [saintedlama/passport-local-mongoose#267]
Hi,

having issues with username case, I was exploring the code and figured out that a plugin option was implemented: `usernameCaseInsensitive` defaults to false, but was not mentioned in the 'Options' section of the Readme.md.

**Comment by vck3000** [comment]
Bump! I found this by perusing the codebase too, and this feature is exactly what I was looking for. It would be great to have this documented. I can throw up a PR if approved.

**Comment by saintedlama** [comment]
A PR would be great👍
