### ISSUE TITLE
How to return error message to login page?

### ISSUE THREAD

**Issue by slim-hmidi** [saintedlama/passport-local-mongoose#276]
I'm trying to use `passport.authenticate('local')` to test some simple application but I struggled a simple problem when a user enter a wrong username or password.
I' m not able to send the error message to `login` page. According to the example mentioned in the repository I didn't find any detail about that. 
https://github.com/saintedlama/passport-local-mongoose/blob/faa856ae70c5962197a5c4c5d967277b59ba7bed/examples/login/routes.js#L31
I tried to add `connect-flash` package and use {failureFlash: 'Username or password is wrong` But I didn't succeed to do that.

**Comment by vit134** [comment]
i have the same question

**Comment by denilsonjvv** [comment]
do failureFlash= true, I'll try to show you how my callback works tomorrow.

**Comment by denilsonjvv** [comment]
People still need help? Ask me
