### ISSUE TITLE
await on .register()

### ISSUE THREAD

**Issue by jcotero** [saintedlama/passport-local-mongoose#278]
I'm running it on Express. When I use CollectionName.register() with cb, it's working.
However, when trying to await or use .then(), it's returning undefined.

`Users.register(newUser, password, function(err, user) { ... }) // works`

`let user = await Users.register(newUser, password) // undefined`

`Retailers.register(newUser, password)
.then( user => {
    // undefined
})`

**Comment by saintedlama** [comment]
Could you check with the newly released 6.0.1 version? My tests say it should work 👍

**Comment by anotheri** [comment]
@jcotero @saintedlama confirmed, it's working on `6.0.1`

**Comment by saintedlama** [comment]
Thanks for checking @anotheri
