### ISSUE TITLE
usernameUnique: false throws error that username is already used

### ISSUE THREAD

**Issue by rsand27** [saintedlama/passport-local-mongoose#280]
I am working on a project that allows the same email to be used to register as long as it has a different role. Roles are student and teacher. I managed to handle logins by doing a look up on the User model first, then calling user.authenticate(). This works fine. It also worked fine for my password reset function. If a teacher tries to use student role, it fails. What I need to be able to do is allow that teacher to be able to have both a student and a teacher account with the same email address, since they could be a student in another course. 

Here is my plugin on the user model:

// Combination of email and role must be unique. Users can have separate student, school employee, and dashboard employee accounts.
User.index({ 'email' : 1, 'role' : 1 }, { unique: true });

User.plugin(passportLocalMongoose, {
    usernameField: 'email',
    // Set usernameUnique to false to avoid a mongodb index on the username column!
    usernameUnique: false,
    limitAttempts: true,
    maxAttempts: 4,
    errorMessages: {
      IncorrectUsernameError: 'Email does not exist'
    }
});

When I use RoboMongo to look at the database, there is no email index by itself. There is the combination index you see above. But the 'UserExistsError' error that gets thrown is from user.register() stating a user with that username already exists. 

![image](https://user-images.githubusercontent.com/17153599/57274936-6ed3f000-7062-11e9-9d1f-29ce3e1e244c.png)

I did comment out the index, delete the index through RoboMongo, then restarted the Node server and it still failed.

I wiped my entire database and set it up again and it still failed. 

I don't necessarily need passport-local-mongoose to enforce unique users. I am checking for existing email/role combinations before passing the new User to register().

Am I doing something wrong or is setting this feature to false not working?

**Comment by saintedlama** [comment]
Perhaps you could store roles in the user model instead of creating two users? Another approach is to prefix the email address with the role. But take care to not use a email valid character for joining rules such as @ or use a postfix which offers a wider range of separation characters.

**Comment by rsand27** [comment]
I went with the second approach and stored a combination field of email-role and set my usernameField to emailRole and that works. I originally was trying to store multiple roles on a user but there were too many edge cases where that failed. Or I just don't know what I'm doing. It's a toss up. Thanks for the solution.
