### ISSUE TITLE
Question on findByUsername query parameters/ error messages

### ISSUE THREAD

**Issue by coldfire84** [saintedlama/passport-local-mongoose#295]
Following [the example in the docs](https://www.npmjs.com/package/passport-local-mongoose#allow-only-active-users-to-authenticate) I've setup a 'user.active field' to help enable account management as part of my solution. I have a couple of questions around extending this, and providing better user feedback in the event these query parameters are not fulfilled when trying to logon:
- Can multiple 'findByUsername' additional query parameters be supplied, i.e. 'active' and 'verified' have to be true, such as the example below:
```
  findByUsername: function(model, queryParameters) {
    // Add additional query parameter - AND condition - active: true
    queryParameters.active = true;
    queryParameters.isVerified= true;
    return model.findOne(queryParameters);
  }
```
- Is it possible to generate a custom error on the parameters not being met (i.e. if user.active is false, notify the user their account has been disabled, if account.isVerified is false notify user they need to verify their account etc).

**Comment by saintedlama** [comment]
I would not try to implement this in the `findByUsername` method but try to pack this functionality after the authentication.

```js
const authenticate = User.authenticate();

passport.use(new LocalStrategy((username, password, cb) => {
  authenticate(username, password, (err, user, error) => {
    if (err) { return cb(err); }

    if (user && !user.isVerified) {
      return cb(null, false, new Error("User is not verified");
    }

    cb(null, user, error);
  });
}));
```

The code above will most probably not work, but I guess you get the idea

**Comment by coldfire84** [comment]
Thanks, I'll give this go.

**Comment by coldfire84** [comment]
This works really well - thank you.
