### ISSUE TITLE
Include type definitions directly in the package

### ISSUE THREAD

**Issue by pbadenski** [saintedlama/passport-local-mongoose#335]
Revisiting #92 reported back in 2015.

A lot has changed since 2015:
 - TypeScript gained massive popularity and is no longer a "bleeding edge technology"
 - both mongodb and mongoose incorporated typescript definition files in their repository

It's proving quite difficult for the users to have type definitions managed separately in DefinitelyTyped repo (see #327, #304, #332). For us it's a challenge each time we need to upgrade mongodb and mongoose dependencies - as the external types lag behind the actual updates of these libraries.

Following mongodb and mongoose - could I suggest including type definitions as part of this repo?

**Comment by saintedlama** [comment]
Would definitely merge that. Also thinking about rewriting the module in typescript to get the types generated. Any help appreciated.

**Comment by pbadenski** [comment]
As pull request is concerned - for the initial step would you be fine if I just move types from DefinitelyTyped to this project? Both are MIT licensed so there's no problem here.
