### ISSUE TITLE
Mongoose 7 does not support some callbacks like in 6.x version and it cause exceptions in passport-local-mongoose

### ISSUE THREAD

**Issue by kubawasikowski** [saintedlama/passport-local-mongoose#369]
Hello,
recent 7 version of mongoose changed quite a lot and passport-local-mongoose have error with latest version:
MongooseError: Query.prototype.exec() no longer accepts a callback
    at model.Query.exec (\node_modules\mongoose\lib\query.js:4281:11)

Thank You for help
Best regards

**Comment by Patrick-Voorhoeve** [comment]
Having the same issue. I've seen suggestions to revert back to 6.1 but this won't work for me. Any other workarounds?
