### ISSUE TITLE
Troubles using "instance.setPassword(pw,cb)" to reset user password

### ISSUE THREAD

**Issue by diosney** [saintedlama/passport-local-mongoose#4]
Hi!

I've trying to use this instance method to reset a user password but it never changes the salt & hash in the db.

This is an extract of the code.

Thanks in advance for you help :D and for this plugin, is really saves time.

```
User.statics.update_profile = function (user_id, new_data, callback) {
    return this.findOne({
        _id: user_id
    }, function (error, doc) {
        if (!error) {
            /*
             * Update password.
             */
            if (new_data.body.new_password == new_data.body.retype_new_password) {
                doc.setPassword(new_data.body.new_password);
                doc.setPassword('new_pass',function(error){
                    console.log(error)
                });
            }
            else {
                console.log('Passwords not match');
            }           
        }
        else {
            callback(error.message);
        }
    });
};
```

**Comment by maxymdev** [comment]
Hi guys. 
I use passport-local-mongoose and I need somehow made a form to change user password. 
can you make an example for me? plz

**Comment by chrisfosterelli** [comment]
@maxymdev I don't think that's an appropriate place for this question since this issue has been resolved. You might want to try Stackoverflow instead!
