### ISSUE TITLE
unrecognized password after mongorestore 

### ISSUE THREAD

**Issue by remotevision** [saintedlama/passport-local-mongoose#42]
Is it expected that after doing a mongodump from localhost, and then a mongorestore to MongoHQ that the password for my users seem to be invalid?

**Comment by evindor** [comment]
Hey, we got the same problem and I traced it to [here](https://github.com/saintedlama/passport-local-mongoose/blob/master/index.js#L52). Depending on `NODE_ENV` `crypto.pbkdf2.length` returns different values - 6 for "development" and 0 for "production". Super weird.

@saintedlama can you please tell us why do you need to perform this check? I was trying to google it but no luck.

**Comment by evindor** [comment]
It turned out for us that there is no link to `NODE_ENV`. It was newrelic. Just requiring it somehow sets `crypto.pbkdf2.length` to 0 :open_mouth:
I guess if @remotevision confirms he had newrelic on prod too this issue can be closed.

**Comment by saintedlama** [comment]
@evindor Thanks for digging that deep to find the bug. Changed behavior in passport-local-mongoose to detect pbkdf2 based on node versions instead of argument length. Released on NPM as `3.1.1`

**Comment by evindor** [comment]
@saintedlama Thanks for quick reaction! But I think you need to unpublish `3.1.1` ASAP and republish it bumping major or at least minor version - this is a breaking change for everyone using `newrelic` in production. Because in fact this release is 3.0 (default `sha256`) for people with newrelic.

**Comment by saintedlama** [comment]
Thanks for the hint! It was a bug fix mentally :cry: - republished a patch level reverted pkg to ensure everyone will get the fix. Will bump major.

**Comment by evindor** [comment]
:+1:

**Comment by saintedlama** [comment]
@remotevision Can you confirm this newrelic thingy?

**Comment by remotevision** [comment]
I do use New Relic!

**Comment by saintedlama** [comment]
@remotevision Then I'll suggest to switch to version 4 of passport-local-mongoose. Thanks all for sorting out that issue :tada:
