### ISSUE TITLE
Create a logout example

### ISSUE THREAD

**Issue by ilanbiala** [saintedlama/passport-local-mongoose#44]
I'm not really sure I'm fully understanding the system here. I noticed there's no logout example and I'm somewhat confused. Can anyone add a couple more good examples?

**Comment by blandman** [comment]
This is working for Google/Twitter/Facebook/LinkedIn passport modules, but not local for me.

**Comment by blandman** [comment]
This works for Google/Twitter/Facebook/LinkedIn passport modules but not here.

**Comment by kelleg1** [comment]
I don't see how this would work when using Apollo as in the case of https://github.com/ooade/next-apollo-auth, as the resolvers in that case do not have access to an Express req object.
