### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by ghost** [saintedlama/passport-local-mongoose#57]
I am specifying email and password matchers in the mongoose schema.

```
var Account = new Schema({
   username: {type: String, match: [/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/, 'Please fill a valid email address']},
   password: {type: String, match: [/(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}/, 'Password not valid']}
});
```

This works when I am trying to register a bad email address, but it doesn't work for the password.

**Comment by CoderSpinoza** [comment]
@Neozaru, could you provide a simple example of using a password validator option in the plugin? Thanks :)

**Comment by Neozaru** [comment]
Hello @CoderSpinoza.

I don't remember exactly, but I forked the repository 4 months ago for this purpose.
https://github.com/Neozaru/passport-local-mongoose

Then I created a custom function for validation and added it in the options :
https://github.com/Neozaru/express-structure/blob/users/models/user.js#L23

**Comment by siboulet** [comment]
#64
