### ISSUE TITLE
Default Messages Should Not Divulge If Username Exists

### ISSUE THREAD

**Issue by caffeinewriter** [saintedlama/passport-local-mongoose#65]
Incorrect Username/Password messages should be generic, like `Incorrect Username or Password`, not specifically divulging if a user account exists, or if the password is simply incorrect as per [OWASP recommendations](https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Authentication_and_Error_Messages).

**Comment by Nijikokun** [comment]
It doesn't matter as you can ascertain this anyway if you have unique username during registration.

**Comment by caffeinewriter** [comment]
Even still, it's another hurdle for potential attackers to overcome before actually ascertaining if a username does exist.

**Comment by Nijikokun** [comment]
Attackers don't attempt login first, they check whether they are registered, then they do the brute forcing. Aside from this the other way attackers gather access is to get the database itself but that's another can of worms.

**Comment by caffeinewriter** [comment]
Fair enough, but as a general rule of thumb, it's a good idea to follow OWASP recommendations.

**Comment by Nijikokun** [comment]
I have no idea why OWASP never responds to discussions... but here is this note anyway - https://www.owasp.org/index.php/Talk:Authentication_Cheat_Sheet#Correct_Response_Example

**Comment by saintedlama** [comment]
My intent was not that these error messages would be displayed to the user. In the next version of passport-local-mongoose these errors and error messages will get refactored to make it hard for developers using passport-local-mongoose to divulge authentication error details.
