### ISSUE TITLE
mongoose save lack item

### ISSUE THREAD

**Issue by zwb-ict** [saintedlama/passport-local-mongoose#75]
model: 
```
var mongoose = require('mongoose'),
    passportLocalMongoose = require('passport-local-mongoose');

var userSchema = mongoose.Schema({
    local : {
        name: String,
        email: String,
        password: String
    }
});

userSchema.plugin(passportLocalMongoose, { usernameField: "email",
                                           usernameLowerCase: true });

var User = mongoose.model('User', userSchema);

module.exports = User;
```

control:
``` 
var authSignup = function(req, res, next) {
        User.register(new User({ name: req.body.name, email: req.body.email }),
                      req.body.password, function(err) {
                          if (err) {
                              req.session.flash = {
                                  type: 'danger',
                                  intro: 'Signup error!',
                                  message: err.message
                              };
                              res.redirect(303, 'new');
                              return;
                          }
                          passport.authenticate('local')(req, res, function() {
                              res.redirect(303, '/users/' + req.user._id);
                          });
                      });
    };
```

user output:

> user: { _id: 55589a33d09d448b47cad663,
  salt: 'cac36dd9c1004ab8452ccbeb0e58539eb694260fbf2416e6a3a6a13cf06295a2',
  hash: 'f6dee71ac1e88e218e970c63bc27adaf244ff9075d3a1dbb44c30c8359572f1cf234759cae649fdac2bdea6abf91682f4a523709aaa8177594df27cb6312ecf764954572da2b25c22be27036807bc04c689284df0d9d1b27a552da967dd2022bd48d779abfbcfb594065d21a1aedc39068597c899f343b7b2936b0d2a4246423e8da32c52fc0c13b79a5cb29066478316d51b2b5fd646bd68c0e846b01dc1f543eb9bf9b27634ff98f4dc14f352f790485d80b2b3ed77c756e04889a7fa521fc34f8f269e761059d93653e48c7b55a7b51736aaa7ce67cf5d4bb5cea1e38d9400f8c06236f6d6618f20f7bcabd8e5d1cb0d0720038c26a2b25c6ada7221e73cb8cfb694d0f9e08ac289b79ec23fd1a3c096e1ae44cdadfbcb23e345c557d13b78f07d9845c61b3340924c6e0073e6a7c11fb43b58fcdeac4aff8a83987e9478afcfb5eaef980479910ef808f2e0686aeaa36c6118125d64b485fac7b533602af0751fc46409b419bfc366c02291ed8de9b777e74e6fdb00b52b2c70025db156b2f6dd0476f6fc6d30723d73dc63fdb56c847a177ac539d3c567746e2790186e078c88485d3db27b54c6353bdd1695e8dd0c2a4feaae43dde8691dbb54995d68fbf4ce322055247f891e79daf0f31781094dad799c77799a246ddfc74038fb3a3e6da5fe8fc8e9ced0037ab3073868194c4171b18883b04b29f77e2ca2189cdf4',
 email: 'dd@gmail.com',
  __v: 0,
  local: {} }

The item **name**  is lost. I don't know why.

my package.json:

```
 "dependencies": {
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "^1.12.4",
    "connect": "^2.29.2",
    "connect-flash": "^0.1.1",
    "cookie-parser": "^1.3.4",
    "express": "^4.12.3",
    "express-handlebars": "^2.0.1",
    "express-session": "^1.11.2",
    "mongoose": "^4.0.3",
    "morgan": "^1.5.3",
    "passport": "^0.2.1",
    "passport-local": "^1.0.0",
    "passport-local-mongoose": "^1.0.0",
    "passport-remember-me": "0.0.1",
    "session-mongoose": "^0.5.2"
  },
```

Need your help, thank you very much!

**Comment by saintedlama** [comment]
There seems to be an error in your schema

    var userSchema = mongoose.Schema({
       local : {
           name: String,
           email: String,
           password: String
       }
    });

should be:

    var userSchema = mongoose.Schema({
         email: String,
         name: String
    });

salt, hash and are added by passport-local-mongoose so no need to declare them on the schema, password is not needed anyway.

**Comment by zwb-ict** [comment]
@saintedlama Thank you for your help, I did as you told. Now it works OK.
