### ISSUE TITLE
Is there some way to handle wrong log in?

### ISSUE THREAD

**Issue by alexhzr** [saintedlama/passport-local-mongoose#76]
When the authentication fails, it only send a page saying 'Unauthorized' and the 401 status code. How can I handle this?

**Comment by saintedlama** [comment]
This aspect is not handled by passport-local-mongoose but by passport's `authenticate` function.

You could use a authenticate configuration to redirect all failed logins to login

    passport.authenticate('provider', { 
      successRedirect: '/',
      failureRedirect: '/login' 
    });


Passport's documentation has some more details here http://passportjs.org/docs/authenticate

**Comment by alexhzr** [comment]
Yay! Passport's documentation (Custom callback section) had the right answer for me! 

This is how I fixed it https://github.com/alexhzr/BilltasticJS/blob/c6eff993359d064fcf72daacd1e711ddea3615b5/BilltasticJS/routes/login.js#L10-L22. The option @saintedlama provided also works, but idk if it would in my case (Android app, API client).

Thank you so much!
