### ISSUE TITLE
Lock account after number of failed attempts

### ISSUE THREAD

**Issue by vergenzt** [saintedlama/passport-local-mongoose#78]
I'd like to be able to lock a user's account when the number of failed password attempts reaches a certain threshold. I'm currently working on a PR for this in my fork, but I opened this issue to see if you'd be open to merging it in. :)

Let me know! Thanks.

**Comment by vergenzt** [comment]
The way I'm going right now, I'm just adding `options.maxAttempts` (defaulting to `Infinity`), and when the number of failed attempts exceeds that option, authentication fails. I'm also adding a schema method `resetAttempts` (defined on the schema only when `options.limitAttempts` is true) to "unlock" accounts.

**Comment by saintedlama** [comment]
Open for merging, you're doing tests for the new functionality?

**Comment by vergenzt** [comment]
I will be. Just started it yesterday though, so it's not ready yet.

**Comment by vergenzt** [comment]
Do you like the idea of just basing the locked status of account on the `attempts` field? Or would you rather have a separate `locked` field that gets set when that limit is exceeded, and has to be unset?

**Comment by saintedlama** [comment]
One locked field is fine since when querying accounts one does not want to query multiple fields to find out if an account is locked.

**Comment by vergenzt** [comment]
:+1:
