### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by siboulet** [saintedlama/passport-local-mongoose#83]
Any chances of getting a version bump (ie 1.0.1) for people relying on the new configurable algorithm or password validation features that were recently merged?

**Comment by saintedlama** [comment]
Will need a major/minor version bump since hashing algorithm default is set to sha-256 which can break password databases ...

**Comment by siboulet** [comment]
Oh didn't notice that. Not sure why you changed the default to sha-256. Node.js 0.12.4 still defaults to sha1 for pbkdf2. I'd suggest defaulting to Node.js default.

**Comment by saintedlama** [comment]
Default set back to sha1, version bumped. The reason for switching to sha256 was that sha1 is not the most secure hashing algorithm anymore. Default will be changed in a future version

**Comment by lemelon** [comment]
Hey is it possible do login with email or username ? If yes, how can you do that ? Thank you for your help

**Comment by saintedlama** [comment]
You should open a dedicated issue for this since it has nothing to do with the version bump
