### ISSUE TITLE
Login with username or email (give the choice to the user)

### ISSUE THREAD

**Issue by lemelon** [saintedlama/passport-local-mongoose#85]
Hey is it possible to login with email or username ? If yes, how can you do that ? Thank you for your help. So on the form it will be "Email or Username".
You can either set the email field or the username field but it don't seem to be possible to set both...
UserSchema.plugin(passportLocalMongoose, {
usernameField: 'email',
usernameLowerCase: true
});

**Comment by saintedlama** [comment]
With the pull request #84 it should be possible. Will have a look at the code

**Comment by lemelon** [comment]
Is the pull request #84 working ? Can i pull the last version of the project with the pull request #84 ? Thanks for the nice work !!

**Comment by saintedlama** [comment]
Fixed by #84
