### ISSUE TITLE
custom missingUsernameError

### ISSUE THREAD

**Issue by scottzirkel** [saintedlama/passport-local-mongoose#87]
I'm setting a custom error message for the username, but when I do it appends the field name to the end.

````
var options = {
  missingUsernameError: "Username be gone, yo.",
}

Account.plugin(passportLocalMongoose, options);
````

This gives me `Username be gone, yo. username`.

If I use `missingUsernameError: "%s be gone, yo."` I get: `username be gone, yo.`

What is causing that stray **username**?

Note: that's not the actual error message, just testing it.

**Comment by fhemberger** [comment]
ref https://github.com/saintedlama/passport-local-mongoose/issues/65#issuecomment-77759714.
