### ISSUE TITLE
wrong error message while maxAttempts not reached

### ISSUE THREAD

**Issue by programming-kid** [saintedlama/passport-local-mongoose#89]
hi
 i was trying out this plug-in but i found one anomaly when ```    limitAttempts: true,
    maxAttempts: 3 ``` is set ,

 If u give wrong password it gives following message ``` Account locked due to too many failed login attempts``` even if this is first attempt and max attempt is not reached 

i think problem is on line 147 in ```  lib/passport-local-mongoose.js ```

@vergenzt, @saintedlama   can you have a look

thanks

**Comment by saintedlama** [comment]
You're right the check there is a bit "dirty"

Link to line: https://github.com/saintedlama/passport-local-mongoose/blob/master/lib/passport-local-mongoose.js#L149

**Comment by programming-kid** [comment]
here is what i have come up with 
```javascript
 if (options.attemptsField >= options.maxAttempts) {
    return cb(null, false, { message: options.tooManyAttemptsError });
 } else {
     return cb(null, false, { message: options.incorrectPasswordError });
 }
```

**Comment by vergenzt** [comment]
Yeah, sorry that was my bad. :( Fixing now...
