### ISSUE TITLE
how would i authenticate an admin user?

### ISSUE THREAD

**Issue by tsm91** [saintedlama/passport-local-mongoose#91]
@saintedlama How can i check if `userSchema.admin` is true before successful authentication on admin login?

**Comment by saintedlama** [comment]
I would add an express middleware before handing requests over to passport.

I a typical passport-local-mongoose setup you'll have some login route configured as

```javascript
router.post('/login', passport.authenticate('local'), function(req, res) {
  res.redirect('/');
});
```

You could add a requireAdmin custom middleware function before `passport.authenticate('local')`

```javascript
router.post('/login', requireAdmin(), passport.authenticate('local'), function(req, res) {
  res.redirect('/');
});
```

The `requireAdmin` middlware has the responsibility to check if the model has an admin field set to true

```javascript
function requireAdmin() {
  return function(req, res, next) {
    User.findOne({ req.body.username }, function(err, user) {
      if (err) { return next(err); }

      if (!user) { 
        // Do something - the user does not exist
      }

      if (!user.admin) { 
        // Do something - the user exists but is no admin user
      }

      // Hand over control to passport
      next();
    });
  }
}
```

**Comment by tsm91** [comment]
Yeah, sorry for the stupid question :) It works pretty well.

i was just wondering if it is possible to do this check after passport queried the db but before authenticated to avoid this extra db travel. With this i will also have to make another middleware / extend this one to check if a logged in user is an admin or not. like `req.user.admin`
